apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: b84e5922-0369-46d0-a838-e98a1a312e8c
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-document-type
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/document_type
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/document_type
